### ISSUE TITLE
Text Is Appearing all weird

### ISSUE THREAD

**Issue by mmarco2121** [boubounokefalos/dotfiles_moon#1]
This set up is great! I tried applying to my system (I'm fairly new to i3) but my font is showing up almost grainy, hard to read. I changed it in the configs.  Also cannot get the lock screen to work.

**Comment by boubounokefalos** [comment]
Hello mate,

as stated in the README.md 

> "PS: This is optimal for my small laptop (**1280x800**) but I'm not sure it will look that good in higher resolutions :)"

which pretty much means that anything above that will look small (I already use small font size so you probably need to oversize numbers a bit for ≥ FHD)
In general you need to adjust the visuals to your screen size :)

Now as for the i3lock-fancier: IF you have compiled it properly, you must pay attention to the configs/files needed.

- /home/USERNAME/lock/lock_white.png

- /home/USERNAME/lock/make_lock_bg.sh

In make_lock_bg.sh change 1280x800 to your resolution:
`convert "$IMAGE" -resize 1280x800^ -gravity center -extent 1280x800 $IMAGE`

Then edit this line at /home/USERNAME/.bash.rc:|

> `#Lockscreen config

> export WALLPAPER="$HOME/wallpaper/moon_wallpaper.jpg"

> export LOCKSCREEN_IMAGE="$HOME/wallpaper/moon_wallpaper.jpg"`

where in $HOME/wallpaper/moon_wallpaper.jpg you can set your path to your wallpaper image.

Finally we have the config file of i3lock-fancier which is located at /home/USERNAME/.config/i3lock-fancier/config.ini. Make sure you have this also.

The above are system-specific for Ubuntu 18.04 but you can adapt them with minor tweaks to other distros too xD

PS: For Polybar, Dunst etc I Use the Comfortaa and FontAwesome fonts :)

**Comment by mmarco2121** [comment]
@boubounokefalos thanks for the reply. The Polybar font works but my system font is now all weird. Including in Firefox. 

I still cannot get i3 lock to work to show any images. As well the shutdown menu does not display. It opens the correct workspace but it is blank and accepts no controls.

**Comment by boubounokefalos** [comment]
@mmarco2121 your system's fonts are not defined by these files, only polybar/urxvt ones :)

Regarding the i3lock-fancier, please re-check that you have set proper paths for the images (I had the same issue when I first installed it). It is vital for the Oblogout-fork shutdown menu to put [these](https://github.com/boubounokefalos/dotfiles_moon/tree/master/.themes/dd_theme/oblogout) images to /home/USERNAME/.themes/dd_theme/oblogout/ directory AND get the [oblogout.conf](https://github.com/boubounokefalos/dotfiles_moon/blob/master/etc/oblogout.conf) on /etc/ directory.

PS: Are you sure you installed i3lock-fancier? Not the stock I3lock

**Comment by mmarco2121** [comment]
@boubounokefalos  thanks! Turns out I was missing oblogout for the lock screen options. The font rendering is still an issue.
